openapi: 3.0.3
info:
  title: API
  version: 1.0.0
paths:
  /greeting:
    get:
      summary: Get a greeting message
      operationId: getGreetingMessage
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
      tags:
        - Greetings
  /tasks:
    post:
      summary: Create new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskRequest'
      responses:
        '201':
          description: Task created with success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        '400':
          description: Invalid request
    get:
      summary: List all tasks
      responses:
        '200':
          description: Tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaskResponse'

components:
  schemas:
    TaskResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        detail:
          type: string
        createdAt:
          type: string
          format: date-time
        done:
          type: boolean
    TaskRequest:
      type: object
      properties:
        detail:
          type: string
      required:
        - detail
