openapi: 3.0.3
info:
  title: API
  version: 1.0.0
paths:
  /greeting:
    get:
      summary: Get a greeting message
      operationId: getGreetingMessage
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
      tags:
        - Greetings
