databaseChangeLog:

  - changeSet:
      id: 01-create-person-sequence
      author: "lorival"
      changes:
        - createSequence:
            sequenceName: "person_sequence"
            startValue: 1
            incrementBy: 1
            allocationSize: 1

  - changeSet:
      id: 02-create-person-table
      author: lorival
      changes:
        - createTable:
            tableName: persons
            columns:
              - column:
                  name: id
                  type: bigint
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: name
                  type: varchar(255)
                  constraints:
                    nullable: false
              - column:
                  name: created_at
                  type: timestamp
                  constraints:
                    nullable: false
              - column:
                  name: age
                  type: int
                  constraints:
                    nullable: false
