openapi: 3.0.0
info:
  title: Person API
  version: 1.0.0
servers:
  - url: /api
paths:
  /hello-world:
    get:
      tags:
        - HelloWorld
      summary: Returns the string hello-world
      responses:
        200:
          description: Successful operation
          content:
            text/plain:
              schema:
                type: string
                example: hello-world
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /persons:
    get:
      tags:
        - Persons
      summary: Lists all persons with pagination
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 0
          description: Page number
        - in: query
          name: pageSize
          schema:
            type: integer
            default: 10
          description: Number of items per page
      responses:
        200:
          description: Paginated list of persons
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalItems:
                    type: integer
                    example: 25
                  totalPages:
                    type: integer
                    example: 3
                  currentPage:
                    type: integer
                    example: 1
                  persons:
                    type: array
                    items:
                      $ref: '#/components/schemas/PersonResponse'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - Persons
      summary: Creates a new person
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePersonRequest'
      responses:
        201:
          description: Person created successfully
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - Persons
      summary: Updates an existing person
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePersonRequest'
      responses:
        204:
          description: No content
        404:
          description: Person not found
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    CreatePersonRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        age:
          type: integer
    UpdatePersonRequest:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
        name:
          type: string
        age:
          type: integer
    PersonResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        age:
          type: integer
    Error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
